
## import SETTINGS

include $(THEKLAROOT)/tests/Makefile.common

### SOUCES (TESTS)

TESTSUITES = \
	../TestInit.h \
	TestInputClient.h \
	TestOutputClient.h

## import RULES

include $(THEKLAROOT)/tests/Makefile.rules
