
## import SETTINGS

include $(THEKLAROOT)/tests/Makefile.common

### SOUCES (TESTS)

TESTSUITES = \
	../TestInit.h \
	TestLog.h \
	TestQtAdapterFactory.h \
	TestQtAdapter.h \
	TestQtAdapterUtils.h \
	TestXmlElementData.h \
	TestBase64.h	 \
	TestObservable.h \
	TestObserver.h \
	TestXmlElement.h \
	TestXmlFactory.h \
	TestXmlElementInfo.h \
	TestXmlSubDocument.h \
	TestXmlDocument.h \
	TestDatabaseConn.h \
	TestXmlConfigFileDocument.h \
	TestQtObject.h \
	TestQtSignal.h \
	TestQtObjectUtils.h \
	TestTypeConverter.h \
	TestQtProperty.h \
	TestOivField.h \
	TestXmlTrashDocument.h \
	TestQDPluginUtils.h \
	TestXmlDatabaseDocument.h


## import RULES

include $(THEKLAROOT)/tests/Makefile.rules
